import { Type } from 'fsuipc';

import { OffsetList } from '@shared/offset-list';
import { Offset } from '@shared/offset';
import { OffsetCategory } from '@shared/offset-category';

export const engine3: OffsetList = {
  engine3ThrottleLever: new Offset({
    value: 0x9BC,
    name: 'engine3ThrottleLever',
    category: OffsetCategory.ENGINE,
    description: 'engine 3 throttle lever - percent - negative = reverse',
    convert: 'Math.round({VAL} < 0 ? {VAL} / 4096 * 100 : {VAL} / 16384 * 100)',
    type: Type.Int16,
    permission: 'r',
  }),
  engine3PropLever: new Offset({
    value: 0x9BE,
    name: 'engine3PropLever',
    category: OffsetCategory.ENGINE,
    description: 'engine 3 prop lever - percent - negative = reverse',
    convert: 'Math.round({VAL} < 0 ? {VAL} / 4096 * 100 : {VAL} / 16384 * 100)',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine3MixtureLever: new Offset({
    value: 0x9C0,
    name: 'engine3MixtureLever',
    category: OffsetCategory.ENGINE,
    description: 'engine 3 prop lever - percent',
    convert: '{VAL} / 16384 * 100',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine3StarterSwitchPosition: new Offset({
    value: 0x9C2,
    name: 'engine3StarterSwitchPosition',
    category: OffsetCategory.ENGINE,
    description: 'engine3 start switch position - JET: 0=off 1=start 2=gen/alt - PROP: 0=off 1=right 2=left 3=both 4=start',
    type: Type.UInt16,
    permission: 'rw',
  }),
  engine3Firing: new Offset({
    value: 0x9C4,
    name: 'engine3Firing',
    category: OffsetCategory.ENGINE,
    description: 'engine 3 combustion',
    convert: '!!{VAL}',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine3N2: new Offset({
    value: 0x9C6,
    name: 'engine3N2',
    category: OffsetCategory.ENGINE,
    description: 'engine 3 N2 - also helo RPM %',
    convert: '{VAL} / 16384 * 100',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine3N1: new Offset({
    value: 0x9C8,
    name: 'engine3N1',
    category: OffsetCategory.ENGINE,
    description: 'engine 3 N1 - also helo RPM %',
    convert: '{VAL} / 16384 * 100',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine3PropRPM: new Offset({
    value: 0x9C8,
    name: 'engine3PropRPM',
    category: OffsetCategory.ENGINE,
    description: 'derive RPM by multiplying by  - negative = counter-rotating propeller',
    convert: '{VAL} / 16384 / 65536',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine3ThrottleLeverControl: new Offset({
    value: 0x9CA,
    name: 'engine3ThrottleLeverControl',
    category: OffsetCategory.ENGINE,
    description: 'engine3 throttle lever control - -4096 to +16384',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine3FuelFlowLbHourSSL: new Offset({
    value: 0x9D0,
    name: 'engine3FuelFlowLbHourSSL',
    category: OffsetCategory.ENGINE,
    description: 'engine3 fuel flow (lb per hour, sea level)',
    convert: '{VAL} / 128',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine3AntiIce: new Offset({
    value: 0x9E2,
    name: 'engine3AntiIce',
    category: OffsetCategory.ENGINE,
    description: 'engine3 anti-ice/carb heat active',
    convert: '!!{VAL}',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine3OilTemp: new Offset({
    value: 0x9E8,
    name: 'engine3OilTemp',
    category: OffsetCategory.ENGINE,
    description: 'engine3 oil temp - celsius',
    convert: 'Math.round({VAL} * 140 / 16384)',
    type: Type.Int16,
    permission: 'r',
  }),
  engine3OilPres: new Offset({
    value: 0x9EA,
    name: 'engine3OilPres',
    category: OffsetCategory.ENGINE,
    description: 'engine3 oil pressure - PSI',
    convert: 'Math.round({VAL} * 55 / 16384)',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine3PressureRatio: new Offset({
    value: 0x9EC,
    name: 'engine3PressureRatio',
    category: OffsetCategory.ENGINE,
    description: 'engine3 pressure ratio',
    convert: '{VAL} * 1.6 / 16384',
    type: Type.Int16,
    permission: 'r',
  }),
  engine3EGT: new Offset({
    value: 0x9EE,
    name: 'engine3EGT',
    category: OffsetCategory.ENGINE,
    description: 'engine3 exhaust gas temperature - Trust only on jet engine - celsius',
    convert: 'Math.round({VAL} * 860 / 16384)',
    type: Type.Int16,
    permission: 'r',
  }),
  engine3MP: new Offset({
    value: 0x9F0,
    name: 'engine3MP',
    category: OffsetCategory.ENGINE,
    description: 'engine3 manifold pressure - inHg',
    convert: '{VAL} / 1024',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine3RPMScaler: new Offset({
    value: 0x9F8,
    name: 'engine3RPMScaler',
    category: OffsetCategory.ENGINE,
    description: 'engine3 RPM Scaler - props: used to calculate RPM',
    type: Type.Int16,
    permission: 'r',
  }),
  engine3OilQuantity: new Offset({
    value: 0xA00,
    name: 'engine3OilQuantity',
    category: OffsetCategory.ENGINE,
    description: 'engine3 oil quantity - percent',
    convert: 'Math.round({VAL} / 16384 * 100)',
    type: Type.Int32,
    permission: 'r',
  }),
  engine3Vibration: new Offset({
    value: 0xA04,
    name: 'engine3Vibration',
    category: OffsetCategory.ENGINE,
    description: 'engine3 vibration',
    convert: 'Math.round({VAL} * 5 / 16384)',
    type: Type.Int32,
    permission: 'r',
  }),
  engine3HydPres: new Offset({
    value: 0xA08,
    name: 'engine3HydPres',
    category: OffsetCategory.ENGINE,
    description: 'engine3 hydraulic pressure - PSI',
    convert: '{VAL} / 4',
    type: Type.Int32,
    permission: 'r',
  }),
  engine3HydQuantity: new Offset({
    value: 0xA0C,
    name: 'engine3HydQuantity',
    category: OffsetCategory.ENGINE,
    description: 'engine3 hydraulic quantity - percent',
    convert: '{VAL} / 16384 * 100',
    type: Type.Int32,
    permission: 'r',
  }),
  engine3CHT: new Offset({
    value: 0xA18,
    name: 'engine3CHT',
    category: OffsetCategory.ENGINE,
    description: 'engine3 cylinder head temperature - F',
    type: Type.Double,
    permission: 'r',
  }),
  engine3ITT: new Offset({
    value: 0xA20,
    name: 'engine3ITT',
    category: OffsetCategory.ENGINE,
    description: 'engine3 turbine temperature - C',
    convert: '{VAL} / 16384',
    type: Type.Int32,
    permission: 'r',
  }),
  engine3Torque: new Offset({
    value: 0xA24,
    name: 'engine3Torque',
    category: OffsetCategory.ENGINE,
    description: 'engine3 torque - trust only for helo - percent',
    convert: '{VAL} / 16384 * 100',
    type: Type.Int32,
    permission: 'r',
  }),
  engine3FuelPres: new Offset({
    value: 0xA28,
    name: 'engine3FuelPres',
    category: OffsetCategory.ENGINE,
    description: 'engine3 fuel pressure - PSI',
    convert: '{VAL} / 144',
    type: Type.Int32,
    permission: 'r',
  }),
  engine3FuelUsedSinceStart: new Offset({
    value: 0xA3C,
    name: 'engine3FuelUsedSinceStart',
    category: OffsetCategory.ENGINE,
    description: 'engine3 used fuel since start - lb',
    type: Type.Single,
    permission: 'r',
  }),
  engine3FuelElapsedTime: new Offset({
    value: 0xA40,
    name: 'engine3FuelElapsedTime',
    category: OffsetCategory.ENGINE,
    description: 'engine3 fuel elapsed time - h',
    type: Type.Single,
    permission: 'r',
  }),
  engine3FuelFlowLbHour: new Offset({
    value: 0xA48,
    name: 'engine3FuelFlowLbHour',
    category: OffsetCategory.ENGINE,
    description: 'engine3 fuel elapsed time - lb/h',
    type: Type.Double,
    permission: 'r',
  }),
  engine3TorqueFtLb: new Offset({
    value: 0xA50,
    name: 'engine3TorqueFtLb',
    category: OffsetCategory.ENGINE,
    description: 'engine3 fuel elapsed time - ft lb',
    type: Type.Single,
    permission: 'r',
  }),
};
