export enum OffsetCategory {
  APU = 'APU',
  AUTOPILOT = 'autopilot',
  COCKPIT = 'cockpit',
  CONTROLS = 'controls',
  ELECTRIC = 'electric',
  ENGINE = 'engine',
  ENVIRONMENT = 'environment',
  FAILURE = 'failure',
  FUEL = 'fuel',
  HELICOPTER = 'helicopter',
  ICING = 'icing',
  PLANE = 'plane',
  POSITION_ATTITUDE = 'position_attitude',
  PRESSURISATION = 'pressurisation',
  PUSHBACK = 'pushback',
  RADIOS = 'radios',
  RUNWAY = 'runway',
  SIMULATION = 'simulation',
  WEATHER = 'weather',
}
