import { Type } from 'fsuipc';

import { OffsetCategory } from '@shared/offset-category';
import { OffsetList } from '@shared/offset-list';
import { Offset } from '@shared/offset';

export const controls: OffsetList = {
  autoRudder: new Offset({
    value: 0x278,
    name: 'autoRudder',
    category: OffsetCategory.CONTROLS,
    description: 'auto coordination',
    convert: '!!{VAL}',
    type: Type.Int16,
    permission: 'rw',
  }),
  leftAileronDeflection: new Offset({
    value: 0x3B0,
    name: 'leftAileronDeflection',
    category: OffsetCategory.CONTROLS,
    description: 'left aileron deflection - radians',
    type: Type.Double,
    permission: 'r',
  }),
  rightAileronDeflection: new Offset({
    value: 0x3B8,
    name: 'rightAileronDeflection',
    category: OffsetCategory.CONTROLS,
    description: 'right aileron deflection - radians',
    type: Type.Double,
    permission: 'r',
  }),
  rotorClutchSwitch: new Offset({
    value: 0x889,
    name: 'rotorClutchSwitch',
    category: OffsetCategory.CONTROLS,
    description: 'rotor clutch switch',
    convert: '!!{VAL}',
    type: Type.Byte,
    permission: 'rw',
  }),
  propellerPitchControl: new Offset({
    value: 0xAF0,
    name: 'propellerPitchControl',
    category: OffsetCategory.CONTROLS,
    description: '0=fixed, 1=auto, 2=manual',
    type: Type.UInt16,
    permission: 'rw',
  }),
  elevatorPositionControl: new Offset({
    value: 0xBB2,
    name: 'elevatorPositionControl',
    description: 'elevator position control - percent',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int16,
    permission: 'rw',
  }),
  elevatorIndicator: new Offset({
    value: 0xBB4,
    name: 'elevatorIndicator',
    description: 'elevator indicator',
    category: OffsetCategory.CONTROLS,
    type: Type.Int16,
    permission: 'r',
  }),
  aileronPositionControl: new Offset({
    value: 0xBB6,
    name: 'aileronPositionControl',
    description: 'aileron position control - percent',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int16,
    permission: 'rw',
  }),
  aileronIndicator: new Offset({
    value: 0xBB8,
    name: 'aileronIndicator',
    description: 'aileron indicator',
    category: OffsetCategory.CONTROLS,
    type: Type.Int16,
    permission: 'r',
  }),
  rudderPositionControl: new Offset({
    value: 0xBBA,
    name: 'rudderPositionControl',
    description: 'rudder position control - percent',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int16,
    permission: 'rw',
  }),
  rudderIndicator: new Offset({
    value: 0xBBC,
    name: 'rudderIndicator',
    description: 'rudder indicator',
    category: OffsetCategory.CONTROLS,
    type: Type.Int16,
    permission: 'r',
  }),
  elevatorTrimPositionControl: new Offset({
    value: 0xBC0,
    name: 'elevatorTrimPositionControl',
    description: 'elevator trim position control - percent',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int16,
    permission: 'rw',
  }),
  elevatorTrimIndicator: new Offset({
    value: 0xBC2,
    name: 'elevatorTrimIndicator',
    description: 'elevator trim indicator',
    category: OffsetCategory.CONTROLS,
    type: Type.Int16,
    permission: 'r',
  }),
  leftBrakeApplication: new Offset({
    value: 0xBC4,
    name: 'leftBrakeApplication',
    description: 'left brake application pressure - percent - will match 100% if parking brake on',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int16,
    permission: 'r',
  }),
  rightBrakeApplication: new Offset({
    value: 0xBC6,
    name: 'rightBrakeApplication',
    description: 'right brake application pressure - percent - will match 100% if parking brake on',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int16,
    permission: 'r',
  }),
  parkingBrake: new Offset({
    value: 0xBC8,
    name: 'parkingBrake',
    description: 'parking brake active',
    category: OffsetCategory.CONTROLS,
    convert: 'typeof {VAL} === `boolean` ? {VAL} ? 32767 : 0 : {VAL} >= 32767',
    type: Type.Int16,
    permission: 'r',
  }),
  brakingIndicator: new Offset({
    value: 0xBCA,
    name: 'brakingIndicator',
    description: 'braking indicator',
    category: OffsetCategory.CONTROLS,
    convert: 'appliedBrakes',
    mapping: true,
    type: Type.Int16,
    permission: 'r',
  }),
  spoilersArm: new Offset({
    value: 0xBCC,
    name: 'spoilersArm',
    description: 'spoilers arm indicator',
    category: OffsetCategory.CONTROLS,
    convert: '!!{VAL}',
    type: Type.Int32,
    permission: 'rw',
  }),
  spoilersControl: new Offset({
    value: 0xBD0,
    name: 'spoilersControl',
    description: 'spoilers control - percent',
    category: OffsetCategory.CONTROLS,
    convert: 'spoilersControl',
    mapping: true,
    type: Type.Int32,
    permission: 'rw',
  }),
  spoilerLeftPosition: new Offset({
    value: 0xBD4,
    name: 'spoilerLeftPosition',
    description: 'left spoiler position - percent',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int32,
    permission: 'rw',
  }),
  spoilerRightPosition: new Offset({
    value: 0xBD8,
    name: 'spoilerRightPosition',
    description: 'right spoiler position - percent',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int32,
    permission: 'rw',
  }),
  flapsControl: new Offset({
    value: 0xBDC,
    name: 'flapsControl',
    description: 'flaps deployment - percent - for steps, depends on 0x3BFA',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int32,
    permission: 'rw',
  }),
  flapsLeftPosition: new Offset({
    value: 0xBE0,
    name: 'flapsLeftPosition',
    description: 'left flaps position indicator - percent - to get angle, depends on max',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int32,
    permission: 'r',
  }),
  flapsRightPosition: new Offset({
    value: 0xBE0,
    name: 'flapsRightPosition',
    description: 'right flaps position indicator - percent - to get angle, depends on max',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int32,
    permission: 'r',
  }),
  gearControl: new Offset({
    value: 0xBE8,
    name: 'gearControl',
    description: 'gear deploy - percent',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int32,
    permission: 'rw',
  }),
  gearNosePosition: new Offset({
    value: 0xBEC,
    name: 'gearNosePosition',
    description: 'nose gear deploy - percent',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int32,
    permission: 'r',
  }),
  gearRightPosition: new Offset({
    value: 0xBF0,
    name: 'gearRightPosition',
    description: 'nose gear deploy - percent',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int32,
    permission: 'r',
  }),
  gearLeftPosition: new Offset({
    value: 0xBF4,
    name: 'gearLeftPosition',
    description: 'nose gear deploy - percent',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int32,
    permission: 'r',
  }),
  flapsHandleIndex: new Offset({
    value: 0xBFC,
    name: 'flapsHandleIndex',
    description: '0 = full up',
    category: OffsetCategory.CONTROLS,
    type: Type.Byte,
    permission: 'rw',
  }),
  rightToeBrakeControl: new Offset({
    value: 0xC00,
    name: 'rightToeBrakeControl',
    description: 'right toe brake application - percent',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 2)',
    type: Type.Byte,
    permission: 'rw',
  }),
  leftToeBrakeControl: new Offset({
    value: 0xC01,
    name: 'leftToeBrakeControl',
    description: 'left toe brake application - percent',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 2)',
    type: Type.Byte,
    permission: 'rw',
  }),
  aileronTrimPosition: new Offset({
    value: 0xC02,
    name: 'aileronTrimPosition',
    description: 'aileron trim position - percent - can be negative',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int16,
    permission: 'rw',
  }),
  rudderTrimPosition: new Offset({
    value: 0xC04,
    name: 'rudderTrimPosition',
    description: 'rudder trim position - percent - can be negative',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int16,
    permission: 'rw',
  }),
  steeringTillerCalibratedValue: new Offset({
    value: 0xC08,
    name: 'steeringTillerCalibratedValue',
    description: 'steering tiller calibrated value - percent - can be negative',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int16,
    permission: 'r',
  }),
  rudderCalibratedvalue: new Offset({
    value: 0xC0A,
    name: 'rudderCalibratedvalue',
    description: 'rudder calibrated value - percent - can be negative',
    category: OffsetCategory.CONTROLS,
    convert: 'Math.round({VAL} / 16383 * 100)',
    type: Type.Int16,
    permission: 'r',
  }),
  elevon1Deflection: new Offset({
    value: 0x2A00,
    name: 'elevon1Deflection',
    description: 'elevon 1 deflection',
    category: OffsetCategory.CONTROLS,
    type: Type.Double,
    permission: 'r',
  }),
  elevon2Deflection: new Offset({
    value: 0x2A08,
    name: 'elevon2Deflection',
    description: 'elevon 2 deflection',
    category: OffsetCategory.CONTROLS,
    type: Type.Double,
    permission: 'r',
  }),
  elevon3Deflection: new Offset({
    value: 0x2A10,
    name: 'elevon3Deflection',
    description: 'elevon 3 deflection',
    category: OffsetCategory.CONTROLS,
    type: Type.Double,
    permission: 'r',
  }),
  elevon4Deflection: new Offset({
    value: 0x2A18,
    name: 'elevon4Deflection',
    description: 'elevon 4 deflection',
    category: OffsetCategory.CONTROLS,
    type: Type.Double,
    permission: 'r',
  }),
  elevon5Deflection: new Offset({
    value: 0x2A20,
    name: 'elevon5Deflection',
    description: 'elevon 5 deflection',
    category: OffsetCategory.CONTROLS,
    type: Type.Double,
    permission: 'r',
  }),
  elevon6Deflection: new Offset({
    value: 0x2A28,
    name: 'elevon6Deflection',
    description: 'elevon 6 deflection',
    category: OffsetCategory.CONTROLS,
    type: Type.Double,
    permission: 'r',
  }),
  elevon7Deflection: new Offset({
    value: 0x2A30,
    name: 'elevon7Deflection',
    description: 'elevon 7 deflection',
    category: OffsetCategory.CONTROLS,
    type: Type.Double,
    permission: 'r',
  }),
  elevon8Deflection: new Offset({
    value: 0x2A30,
    name: 'elevon8Deflection',
    description: 'elevon 8 deflection',
    category: OffsetCategory.CONTROLS,
    type: Type.Double,
    permission: 'r',
  }),
  foldingWingLeft: new Offset({
    value: 0x2A48,
    name: 'foldingWingLeft',
    description: 'folding right left - percent',
    category: OffsetCategory.CONTROLS,
    convert: 'doublePercentRound',
    mapping: true,
    type: Type.Double,
    permission: 'r',
  }),
  foldingWingRight: new Offset({
    value: 0x2A50,
    name: 'foldingWingRight',
    description: 'folding right right - percent',
    category: OffsetCategory.CONTROLS,
    convert: 'doublePercentRound',
    mapping: true,
    type: Type.Double,
    permission: 'r',
  }),
  canopyOpen: new Offset({
    value: 0x2A50,
    name: 'canopyOpen',
    description: 'canopy open',
    category: OffsetCategory.CONTROLS,
    type: Type.Double,
    permission: 'r',
  }),
  tailWheelLocked: new Offset({
    value: 0x2A90,
    name: 'tailWheelLocked',
    description: 'tail wheel locked',
    category: OffsetCategory.CONTROLS,
    convert: '!!{VAL}',
    type: Type.UInt32,
    permission: 'rw',
  }),
  elevatorDeflection: new Offset({
    value: 0x2E98,
    name: 'elevatorDeflection',
    description: 'elevator deflection - radians +ve up -ve down',
    category: OffsetCategory.CONTROLS,
    type: Type.Double,
    permission: 'r',
  }),
  elevatorTrimDeflection: new Offset({
    value: 0x2EA0,
    name: 'elevatorTrimDeflection',
    description: 'elevator trim deflection - radians +ve up -ve down',
    category: OffsetCategory.CONTROLS,
    type: Type.Double,
    permission: 'rw',
  }),
  aileronDeflection: new Offset({
    value: 0x2EA8,
    name: 'aileronDeflection',
    description: 'aileron deflection - radians +ve right -ve left',
    category: OffsetCategory.CONTROLS,
    type: Type.Double,
    permission: 'r',
  }),
  aileronTrimDeflection: new Offset({
    value: 0x2EB0,
    name: 'aileronTrimDeflection',
    description: 'aileron trim deflection - radians +ve right -ve left',
    category: OffsetCategory.CONTROLS,
    type: Type.Double,
    permission: 'rw',
  }),
  rudderDeflection: new Offset({
    value: 0x2EB8,
    name: 'rudderDeflection',
    description: 'rudder deflection - radians +ve right -ve left',
    category: OffsetCategory.CONTROLS,
    type: Type.Double,
    permission: 'r',
  }),
  rudderTrimDeflection: new Offset({
    value: 0x2EC0,
    name: 'rudderTrimDeflection',
    description: 'rudder trim deflection - radians +ve right -ve left',
    category: OffsetCategory.CONTROLS,
    type: Type.Double,
    permission: 'rw',
  }),
  flightDirectorActive: new Offset({
    value: 0x2EE0,
    name: 'flightDirectorActive',
    category: OffsetCategory.CONTROLS,
    description: 'panel auto-feather arm switch',
    convert: '!!{VAL}',
    type: Type.UInt32,
    permission: 'rw',
  }),
  flightDirectorPitch: new Offset({
    value: 0x2EE8,
    name: 'flightDirectorPitch',
    category: OffsetCategory.CONTROLS,
    description: 'flight director pitch - degrees',
    type: Type.Double,
    permission: 'rw',
  }),
  flightDirectorBank: new Offset({
    value: 0x2EF0,
    name: 'flightDirectorBank',
    category: OffsetCategory.CONTROLS,
    description: 'flight director bank - degrees',
    type: Type.Double,
    permission: 'rw',
  }),
};
