import { Type } from 'fsuipc';

import { OffsetCategory } from '@shared/offset-category';
import { OffsetList } from '@shared/offset-list';
import { Offset } from '@shared/offset';

export const engines: OffsetList = {
  engineType: new Offset({
    value: 0x609,
    name: 'engineType',
    category: OffsetCategory.ENGINE,
    description: 'engine type',
    convert: 'engineType',
    mapping: true,
    type: Type.Byte,
    permission: 'r',
  }),
  hasMixtureControl: new Offset({
    value: 0x780,
    name: 'hasMixtureControl',
    category: OffsetCategory.ENGINE,
    description: 'has mixture control',
    convert: '!!{VAL}',
    type: Type.UInt32,
    permission: 'r',
  }),
  hasCarbHeat: new Offset({
    value: 0x784,
    name: 'hasCarbHeat',
    category: OffsetCategory.ENGINE,
    description: 'has carb heat',
    convert: '!!{VAL}',
    type: Type.UInt32,
    permission: 'r',
  }),
  activeEngine: new Offset({
    value: 0x888,
    name: 'activeEngine',
    category: OffsetCategory.ENGINE,
    description: 'active engine pattern',
    type: Type.BitArray,
    length: 1,
    permission: 'rw',
  }),

  // ENGINE 1

  engine1ThrottleLever: new Offset({
    value: 0x88C,
    name: 'engine1ThrottleLever',
    category: OffsetCategory.ENGINE,
    description: 'engine 1 throttle lever - percent - negative = reverse',
    convert: 'Math.round({VAL} < 0 ? {VAL} / 4096 * 100 : {VAL} / 16384 * 100)',
    type: Type.Int16,
    permission: 'r',
  }),
  engine1PropLever: new Offset({
    value: 0x88E,
    name: 'engine1PropLever',
    category: OffsetCategory.ENGINE,
    description: 'engine 1 prop lever - percent - negative = reverse',
    convert: 'Math.round({VAL} < 0 ? {VAL} / 4096 * 100 : {VAL} / 16384 * 100)',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine1MixtureLever: new Offset({
    value: 0x890,
    name: 'engine1MixtureLever',
    category: OffsetCategory.ENGINE,
    description: 'engine 1 prop lever - percent',
    convert: '{VAL} / 16384 * 100',
    type: Type.UInt16,
    permission: 'rw',
  }),
  engine1StarterSwitchPosition: new Offset({
    value: 0x892,
    name: 'engine1StarterSwitchPosition',
    category: OffsetCategory.ENGINE,
    description: 'engine1 start switch position - JET: 0=off 1=start 2=gen/alt - PROP: 0=off 1=right 2=left 3=both 4=start',
    type: Type.UInt16,
    permission: 'rw',
  }),
  engine1Firing: new Offset({
    value: 0x894,
    name: 'engine1Firing',
    category: OffsetCategory.ENGINE,
    description: 'engine 1 combustion',
    convert: '!!{VAL}',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine1N2: new Offset({
    value: 0x896,
    name: 'engine1N2',
    category: OffsetCategory.ENGINE,
    description: 'engine 1 N2 - also helo RPM %',
    convert: '{VAL} / 16384 * 100',
    type: Type.UInt16,
    permission: 'rw',
  }),
  engine1N1: new Offset({
    value: 0x898,
    name: 'engine1N1',
    category: OffsetCategory.ENGINE,
    description: 'engine 1 N1 - also helo RPM %',
    convert: '{VAL} / 16384 * 100',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine1PropRPM: new Offset({
    value: 0x898,
    name: 'engine1PropRPM',
    category: OffsetCategory.ENGINE,
    description: 'derive RPM by multiplying by  - negative = counter-rotating propeller',
    convert: '{VAL} / 16384 / 65536',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine1ThrottleLeverControl: new Offset({
    value: 0x89A,
    name: 'engine1ThrottleLeverControl',
    category: OffsetCategory.ENGINE,
    description: 'engine1 throttle lever control - -4096 to +16384',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine1FuelFlowLbHourSSL: new Offset({
    value: 0x8A0,
    name: 'engine1FuelFlowLbHourSSL',
    category: OffsetCategory.ENGINE,
    description: 'engine1 fuel flow (lb per hour, sea level)',
    convert: '{VAL} / 128',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine1AntiIce: new Offset({
    value: 0x8B2,
    name: 'engine1AntiIce',
    category: OffsetCategory.ENGINE,
    description: 'engine1 anti-ice/carb heat active',
    convert: '!!{VAL}',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine1OilTemp: new Offset({
    value: 0x8B8,
    name: 'engine1OilTemp',
    category: OffsetCategory.ENGINE,
    description: 'engine1 oil temp - celsius',
    convert: 'Math.round({VAL} * 140 / 16384)',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine1OilPres: new Offset({
    value: 0x8BA,
    name: 'engine1OilPres',
    category: OffsetCategory.ENGINE,
    description: 'engine1 oil pressure - PSI',
    convert: 'Math.round({VAL} * 55 / 16384)',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine1PressureRatio: new Offset({
    value: 0x8BC,
    name: 'engine1PressureRatio',
    category: OffsetCategory.ENGINE,
    description: 'engine1 pressure ratio',
    convert: '{VAL} * 1.6 / 16384',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine1EGT: new Offset({
    value: 0x8BE,
    name: 'engine1EGT',
    category: OffsetCategory.ENGINE,
    description: 'engine1 exhaust gas temperature - Trust only on jet engine - celsius',
    convert: 'Math.round({VAL} * 860 / 16384)',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine1MP: new Offset({
    value: 0x8C0,
    name: 'engine1MP',
    category: OffsetCategory.ENGINE,
    description: 'engine1 manifold pressure - inHg',
    convert: '{VAL} / 1024',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine1RPMScaler: new Offset({
    value: 0x8C8,
    name: 'engine1RPMScaler',
    category: OffsetCategory.ENGINE,
    description: 'engine1 RPM Scaler - props: used to calculate RPM',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine1OilQuantity: new Offset({
    value: 0x8D0,
    name: 'engine1OilQuantity',
    category: OffsetCategory.ENGINE,
    description: 'engine1 oil quantity - percent',
    convert: 'Math.round({VAL} / 16384 * 100)',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine1Vibration: new Offset({
    value: 0x8D4,
    name: 'engine1Vibration',
    category: OffsetCategory.ENGINE,
    description: 'engine1 vibration',
    convert: 'Math.round({VAL} * 5 / 16384)',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine1HydPres: new Offset({
    value: 0x8D8,
    name: 'engine1HydPres',
    category: OffsetCategory.ENGINE,
    description: 'engine1 hydraulic pressure - PSI',
    convert: '{VAL} / 4',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine1HydQuantity: new Offset({
    value: 0x8DC,
    name: 'engine1HydQuantity',
    category: OffsetCategory.ENGINE,
    description: 'engine1 hydraulic quantity - PSI',
    convert: '{VAL} / 16384 * 100',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine1CHT: new Offset({
    value: 0x8E8,
    name: 'engine1CHT',
    category: OffsetCategory.ENGINE,
    description: 'engine1 cylinder head temperature - F',
    type: Type.Double,
    permission: 'r',
  }),
  engine1ITT: new Offset({
    value: 0x8F0,
    name: 'engine1ITT',
    category: OffsetCategory.ENGINE,
    description: 'engine1 turbine temperature - C',
    convert: '{VAL} / 16384',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine1Torque: new Offset({
    value: 0x8F4,
    name: 'engine1Torque',
    category: OffsetCategory.ENGINE,
    description: 'engine1 torque - trust only for helo - percent',
    convert: '{VAL} / 16384 * 100',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine1FuelPres: new Offset({
    value: 0x8F8,
    name: 'engine1FuelPres',
    category: OffsetCategory.ENGINE,
    description: 'engine1 fuel pressure - PSI',
    convert: '{VAL} / 144',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine1ElectricalLoad: new Offset({
    value: 0x8FC,
    name: 'engine1ElectricalLoad',
    category: OffsetCategory.ENGINE,
    description: 'engine1 electrical load - trust only for helo - percent',
    convert: '{VAL} / 16384 * 100',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine1TransmOilPres: new Offset({
    value: 0x900,
    name: 'engine1TransmOilPres',
    category: OffsetCategory.ENGINE,
    description: 'engine1 transmission oil pressure - trust only for helo - PSI',
    convert: '{VAL} / 16384',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine1TransmOilTemp: new Offset({
    value: 0x904,
    name: 'engine1TransmOilTemp',
    category: OffsetCategory.ENGINE,
    description: 'engine1 transmission oil temperature - trust only for helo - C',
    convert: '{VAL} / 16384',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine1RotorRPM: new Offset({
    value: 0x908,
    name: 'engine1RotorRPM',
    category: OffsetCategory.ENGINE,
    description: 'engine1 rotor RPM - trust only for helo - percent',
    convert: '{VAL} / 16384 * 100',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine1FuelUsedSinceStart: new Offset({
    value: 0x90C,
    name: 'engine1FuelUsedSinceStart',
    category: OffsetCategory.ENGINE,
    description: 'engine1 used fuel since start - lb',
    type: Type.Single,
    permission: 'r',
  }),
  engine1FuelElapsedTime: new Offset({
    value: 0x910,
    name: 'engine1FuelElapsedTime',
    category: OffsetCategory.ENGINE,
    description: 'engine1 fuel elapsed time - h',
    type: Type.Single,
    permission: 'r',
  }),
  engine1FuelFlowLbHour: new Offset({
    value: 0x918,
    name: 'engine1FuelFlowLbHour',
    category: OffsetCategory.ENGINE,
    description: 'engine1 fuel elapsed time - lb/h',
    type: Type.Double,
    permission: 'r',
  }),
  engine1TorqueFtLb: new Offset({
    value: 0x920,
    name: 'engine1TorqueFtLb',
    category: OffsetCategory.ENGINE,
    description: 'engine1 fuel elapsed time - ft lb',
    type: Type.Single,
    permission: 'r',
  }),

  // Engine 2

  engine2ThrottleLever: new Offset({
    value: 0x924,
    name: 'engine2ThrottleLever',
    category: OffsetCategory.ENGINE,
    description: 'engine 2 throttle lever - percent - negative = reverse',
    convert: 'Math.round({VAL} < 0 ? {VAL} / 4096 * 100 : {VAL} / 16384 * 100)',
    type: Type.Int16,
    permission: 'r',
  }),
  engine2PropLever: new Offset({
    value: 0x926,
    name: 'engine2PropLever',
    category: OffsetCategory.ENGINE,
    description: 'engine 2 prop lever - percent - negative = reverse',
    convert: 'Math.round({VAL} < 0 ? {VAL} / 4096 * 100 : {VAL} / 16384 * 100)',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine2MixtureLever: new Offset({
    value: 0x928,
    name: 'engine2MixtureLever',
    category: OffsetCategory.ENGINE,
    description: 'engine 2 prop lever - percent',
    convert: '{VAL} / 16384 * 100',
    type: Type.UInt16,
    permission: 'rw',
  }),
  engine2StarterSwitchPosition: new Offset({
    value: 0x92A,
    name: 'engine2StarterSwitchPosition',
    category: OffsetCategory.ENGINE,
    description: 'engine2 start switch position - JET: 0=off 1=start 2=gen/alt - PROP: 0=off 1=right 2=left 3=both 4=start',
    type: Type.UInt16,
    permission: 'rw',
  }),
  engine2Firing: new Offset({
    value: 0x92C,
    name: 'engine2Firing',
    category: OffsetCategory.ENGINE,
    description: 'engine 2 combustion',
    convert: '!!{VAL}',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine2N2: new Offset({
    value: 0x92E,
    name: 'engine2N2',
    category: OffsetCategory.ENGINE,
    description: 'engine 2 N2 - also helo RPM %',
    convert: '{VAL} / 16384 * 100',
    type: Type.UInt16,
    permission: 'rw',
  }),
  engine2N1: new Offset({
    value: 0x930,
    name: 'engine2N1',
    category: OffsetCategory.ENGINE,
    description: 'engine 2 N1 - also helo RPM %',
    convert: '{VAL} / 16384 * 100',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine2PropRPM: new Offset({
    value: 0x930,
    name: 'engine2PropRPM',
    category: OffsetCategory.ENGINE,
    description: 'derive RPM by multiplying by  - negative = counter-rotating propeller',
    convert: '{VAL} / 16384 / 65536',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine2ThrottleLeverControl: new Offset({
    value: 0x932,
    name: 'engine2ThrottleLeverControl',
    category: OffsetCategory.ENGINE,
    description: 'engine2 throttle lever control - -4096 to +16384',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine2FuelFlowLbHourSSL: new Offset({
    value: 0x938,
    name: 'engine2FuelFlowLbHourSSL',
    category: OffsetCategory.ENGINE,
    description: 'engine2 fuel flow (lb per hour, sea level)',
    convert: '{VAL} / 128',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine2AntiIce: new Offset({
    value: 0x94A,
    name: 'engine2AntiIce',
    category: OffsetCategory.ENGINE,
    description: 'engine2 anti-ice/carb heat active',
    convert: '!!{VAL}',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine2OilTemp: new Offset({
    value: 0x950,
    name: 'engine2OilTemp',
    category: OffsetCategory.ENGINE,
    description: 'engine2 oil temp - celsius',
    convert: 'Math.round({VAL} * 140 / 16384)',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine2OilPres: new Offset({
    value: 0x952,
    name: 'engine2OilPres',
    category: OffsetCategory.ENGINE,
    description: 'engine2 oil pressure - PSI',
    convert: 'Math.round({VAL} * 55 / 16384)',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine2PressureRatio: new Offset({
    value: 0x954,
    name: 'engine2PressureRatio',
    category: OffsetCategory.ENGINE,
    description: 'engine2 pressure ratio',
    convert: '{VAL} * 1.6 / 16384',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine2EGT: new Offset({
    value: 0x956,
    name: 'engine2EGT',
    category: OffsetCategory.ENGINE,
    description: 'engine2 exhaust gas temperature - Trust only on jet engine - celsius',
    convert: 'Math.round({VAL} * 860 / 16384)',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine2MP: new Offset({
    value: 0x958,
    name: 'engine2MP',
    category: OffsetCategory.ENGINE,
    description: 'engine2 manifold pressure - inHg',
    convert: '{VAL} / 1024',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine2RPMScaler: new Offset({
    value: 0x960,
    name: 'engine2RPMScaler',
    category: OffsetCategory.ENGINE,
    description: 'engine2 RPM Scaler - props: used to calculate RPM',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine2OilQuantity: new Offset({
    value: 0x968,
    name: 'engine2OilQuantity',
    category: OffsetCategory.ENGINE,
    description: 'engine2 oil quantity - percent',
    convert: 'Math.round({VAL} / 16384 * 100)',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine2Vibration: new Offset({
    value: 0x96C,
    name: 'engine2Vibration',
    category: OffsetCategory.ENGINE,
    description: 'engine2 vibration',
    convert: 'Math.round({VAL} * 5 / 16384)',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine2HydPres: new Offset({
    value: 0x970,
    name: 'engine2HydPres',
    category: OffsetCategory.ENGINE,
    description: 'engine2 hydraulic pressure - PSI',
    convert: '{VAL} / 4',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine2HydQuantity: new Offset({
    value: 0x974,
    name: 'engine2HydQuantity',
    category: OffsetCategory.ENGINE,
    description: 'engine2 hydraulic quantity - percent',
    convert: '{VAL} / 16384 * 100',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine2CHT: new Offset({
    value: 0x980,
    name: 'engine2CHT',
    category: OffsetCategory.ENGINE,
    description: 'engine2 cylinder head temperature - F',
    type: Type.Double,
    permission: 'r',
  }),
  engine2ITT: new Offset({
    value: 0x988,
    name: 'engine2ITT',
    category: OffsetCategory.ENGINE,
    description: 'engine2 turbine temperature - C',
    convert: '{VAL} / 16384',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine2Torque: new Offset({
    value: 0x98C,
    name: 'engine2Torque',
    category: OffsetCategory.ENGINE,
    description: 'engine2 torque - trust only for helo - percent',
    convert: '{VAL} / 16384 * 100',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine2FuelPres: new Offset({
    value: 0x990,
    name: 'engine2FuelPres',
    category: OffsetCategory.ENGINE,
    description: 'engine2 fuel pressure - PSI',
    convert: '{VAL} / 144',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine2FuelUsedSinceStart: new Offset({
    value: 0x9A4,
    name: 'engine2FuelUsedSinceStart',
    category: OffsetCategory.ENGINE,
    description: 'engine2 used fuel since start - lb',
    type: Type.Single,
    permission: 'r',
  }),
  engine2FuelElapsedTime: new Offset({
    value: 0x9A8,
    name: 'engine2FuelElapsedTime',
    category: OffsetCategory.ENGINE,
    description: 'engine2 fuel elapsed time - h',
    type: Type.Single,
    permission: 'r',
  }),
  engine2FuelFlowLbHour: new Offset({
    value: 0x9B0,
    name: 'engine2FuelFlowLbHour',
    category: OffsetCategory.ENGINE,
    description: 'engine2 fuel elapsed time - lb/h',
    type: Type.Double,
    permission: 'r',
  }),
  engine2TorqueFtLb: new Offset({
    value: 0x9B8,
    name: 'engine2TorqueFtLb',
    category: OffsetCategory.ENGINE,
    description: 'engine2 fuel elapsed time - ft lb',
    type: Type.Single,
    permission: 'r',
  }),

  // Engine 3

  engine3ThrottleLever: new Offset({
    value: 0x9BC,
    name: 'engine3ThrottleLever',
    category: OffsetCategory.ENGINE,
    description: 'engine 3 throttle lever - percent - negative = reverse',
    convert: 'Math.round({VAL} < 0 ? {VAL} / 4096 * 100 : {VAL} / 16384 * 100)',
    type: Type.Int16,
    permission: 'r',
  }),
  engine3PropLever: new Offset({
    value: 0x9BE,
    name: 'engine3PropLever',
    category: OffsetCategory.ENGINE,
    description: 'engine 3 prop lever - percent - negative = reverse',
    convert: 'Math.round({VAL} < 0 ? {VAL} / 4096 * 100 : {VAL} / 16384 * 100)',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine3MixtureLever: new Offset({
    value: 0x9C0,
    name: 'engine3MixtureLever',
    category: OffsetCategory.ENGINE,
    description: 'engine 3 prop lever - percent',
    convert: '{VAL} / 16384 * 100',
    type: Type.UInt16,
    permission: 'rw',
  }),
  engine3StarterSwitchPosition: new Offset({
    value: 0x9C2,
    name: 'engine3StarterSwitchPosition',
    category: OffsetCategory.ENGINE,
    description: 'engine3 start switch position - JET: 0=off 1=start 2=gen/alt - PROP: 0=off 1=right 2=left 3=both 4=start',
    type: Type.UInt16,
    permission: 'rw',
  }),
  engine3Firing: new Offset({
    value: 0x9C4,
    name: 'engine3Firing',
    category: OffsetCategory.ENGINE,
    description: 'engine 3 combustion',
    convert: '!!{VAL}',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine3N2: new Offset({
    value: 0x9C6,
    name: 'engine3N2',
    category: OffsetCategory.ENGINE,
    description: 'engine 3 N2 - also helo RPM %',
    convert: '{VAL} / 16384 * 100',
    type: Type.UInt16,
    permission: 'rw',
  }),
  engine3N1: new Offset({
    value: 0x9C8,
    name: 'engine3N1',
    category: OffsetCategory.ENGINE,
    description: 'engine 3 N1 - also helo RPM %',
    convert: '{VAL} / 16384 * 100',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine3PropRPM: new Offset({
    value: 0x9C8,
    name: 'engine3PropRPM',
    category: OffsetCategory.ENGINE,
    description: 'derive RPM by multiplying by  - negative = counter-rotating propeller',
    convert: '{VAL} / 16384 / 65536',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine3ThrottleLeverControl: new Offset({
    value: 0x9CA,
    name: 'engine3ThrottleLeverControl',
    category: OffsetCategory.ENGINE,
    description: 'engine3 throttle lever control - -4096 to +16384',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine3FuelFlowLbHourSSL: new Offset({
    value: 0x9D0,
    name: 'engine3FuelFlowLbHourSSL',
    category: OffsetCategory.ENGINE,
    description: 'engine3 fuel flow (lb per hour, sea level)',
    convert: '{VAL} / 128',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine3AntiIce: new Offset({
    value: 0x9E2,
    name: 'engine3AntiIce',
    category: OffsetCategory.ENGINE,
    description: 'engine3 anti-ice/carb heat active',
    convert: '!!{VAL}',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine3OilTemp: new Offset({
    value: 0x9E8,
    name: 'engine3OilTemp',
    category: OffsetCategory.ENGINE,
    description: 'engine3 oil temp - celsius',
    convert: 'Math.round({VAL} * 140 / 16384)',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine3OilPres: new Offset({
    value: 0x9EA,
    name: 'engine3OilPres',
    category: OffsetCategory.ENGINE,
    description: 'engine3 oil pressure - PSI',
    convert: 'Math.round({VAL} * 55 / 16384)',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine3PressureRatio: new Offset({
    value: 0x9EC,
    name: 'engine3PressureRatio',
    category: OffsetCategory.ENGINE,
    description: 'engine3 pressure ratio',
    convert: '{VAL} * 1.6 / 16384',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine3EGT: new Offset({
    value: 0x9EE,
    name: 'engine3EGT',
    category: OffsetCategory.ENGINE,
    description: 'engine3 exhaust gas temperature - Trust only on jet engine - celsius',
    convert: 'Math.round({VAL} * 860 / 16384)',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine3MP: new Offset({
    value: 0x9F0,
    name: 'engine3MP',
    category: OffsetCategory.ENGINE,
    description: 'engine3 manifold pressure - inHg',
    convert: '{VAL} / 1024',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine3RPMScaler: new Offset({
    value: 0x9F8,
    name: 'engine3RPMScaler',
    category: OffsetCategory.ENGINE,
    description: 'engine3 RPM Scaler - props: used to calculate RPM',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine3OilQuantity: new Offset({
    value: 0xA00,
    name: 'engine3OilQuantity',
    category: OffsetCategory.ENGINE,
    description: 'engine3 oil quantity - percent',
    convert: 'Math.round({VAL} / 16384 * 100)',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine3Vibration: new Offset({
    value: 0xA04,
    name: 'engine3Vibration',
    category: OffsetCategory.ENGINE,
    description: 'engine3 vibration',
    convert: 'Math.round({VAL} * 5 / 16384)',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine3HydPres: new Offset({
    value: 0xA08,
    name: 'engine3HydPres',
    category: OffsetCategory.ENGINE,
    description: 'engine3 hydraulic pressure - PSI',
    convert: '{VAL} / 4',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine3HydQuantity: new Offset({
    value: 0xA0C,
    name: 'engine3HydQuantity',
    category: OffsetCategory.ENGINE,
    description: 'engine3 hydraulic quantity - percent',
    convert: '{VAL} / 16384 * 100',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine3CHT: new Offset({
    value: 0xA18,
    name: 'engine3CHT',
    category: OffsetCategory.ENGINE,
    description: 'engine3 cylinder head temperature - F',
    type: Type.Double,
    permission: 'r',
  }),
  engine3ITT: new Offset({
    value: 0xA20,
    name: 'engine3ITT',
    category: OffsetCategory.ENGINE,
    description: 'engine3 turbine temperature - C',
    convert: '{VAL} / 16384',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine3Torque: new Offset({
    value: 0xA24,
    name: 'engine3Torque',
    category: OffsetCategory.ENGINE,
    description: 'engine3 torque - trust only for helo - percent',
    convert: '{VAL} / 16384 * 100',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine3FuelPres: new Offset({
    value: 0xA28,
    name: 'engine3FuelPres',
    category: OffsetCategory.ENGINE,
    description: 'engine3 fuel pressure - PSI',
    convert: '{VAL} / 144',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine3FuelUsedSinceStart: new Offset({
    value: 0xA3C,
    name: 'engine3FuelUsedSinceStart',
    category: OffsetCategory.ENGINE,
    description: 'engine3 used fuel since start - lb',
    type: Type.Single,
    permission: 'r',
  }),
  engine3FuelElapsedTime: new Offset({
    value: 0xA40,
    name: 'engine3FuelElapsedTime',
    category: OffsetCategory.ENGINE,
    description: 'engine3 fuel elapsed time - h',
    type: Type.Single,
    permission: 'r',
  }),
  engine3FuelFlowLbHour: new Offset({
    value: 0xA48,
    name: 'engine3FuelFlowLbHour',
    category: OffsetCategory.ENGINE,
    description: 'engine3 fuel elapsed time - lb/h',
    type: Type.Double,
    permission: 'r',
  }),
  engine3TorqueFtLb: new Offset({
    value: 0xA50,
    name: 'engine3TorqueFtLb',
    category: OffsetCategory.ENGINE,
    description: 'engine3 fuel elapsed time - ft lb',
    type: Type.Single,
    permission: 'r',
  }),

  // Engine 4

  engine4ThrottleLever: new Offset({
    value: 0xA54,
    name: 'engine4ThrottleLever',
    category: OffsetCategory.ENGINE,
    description: 'engine 4 throttle lever - percent - negative = reverse',
    convert: 'Math.round({VAL} < 0 ? {VAL} / 4096 * 100 : {VAL} / 16384 * 100)',
    type: Type.Int16,
    permission: 'r',
  }),
  engine4PropLever: new Offset({
    value: 0xA56,
    name: 'engine4PropLever',
    category: OffsetCategory.ENGINE,
    description: 'engine 4 prop lever - percent - negative = reverse',
    convert: 'Math.round({VAL} < 0 ? {VAL} / 4096 * 100 : {VAL} / 16384 * 100)',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine4MixtureLever: new Offset({
    value: 0xA58,
    name: 'engine4MixtureLever',
    category: OffsetCategory.ENGINE,
    description: 'engine 4 prop lever - percent',
    convert: '{VAL} / 16384 * 100',
    type: Type.UInt16,
    permission: 'rw',
  }),
  engine4StarterSwitchPosition: new Offset({
    value: 0xA5A,
    name: 'engine4StarterSwitchPosition',
    category: OffsetCategory.ENGINE,
    description: 'engine4 start switch position - JET: 0=off 1=start 2=gen/alt - PROP: 0=off 1=right 2=left 3=both 4=start',
    type: Type.UInt16,
    permission: 'rw',
  }),
  engine4Firing: new Offset({
    value: 0xA5C,
    name: 'engine4Firing',
    category: OffsetCategory.ENGINE,
    description: 'engine 4 combustion',
    convert: '!!{VAL}',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine4N2: new Offset({
    value: 0xA5E,
    name: 'engine4N2',
    category: OffsetCategory.ENGINE,
    description: 'engine 4 N2 - also helo RPM %',
    convert: '{VAL} / 16384 * 100',
    type: Type.UInt16,
    permission: 'rw',
  }),
  engine4N1: new Offset({
    value: 0xA60,
    name: 'engine4N1',
    category: OffsetCategory.ENGINE,
    description: 'engine 4 N1 - also helo RPM %',
    convert: '{VAL} / 16384 * 100',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine4PropRPM: new Offset({
    value: 0xA60,
    name: 'engine4PropRPM',
    category: OffsetCategory.ENGINE,
    description: 'derive RPM by multiplying by  - negative = counter-rotating propeller',
    convert: '{VAL} / 16384 / 65536',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine4ThrottleLeverControl: new Offset({
    value: 0xA62,
    name: 'engine4ThrottleLeverControl',
    category: OffsetCategory.ENGINE,
    description: 'engine4 throttle lever control - -4096 to +16384',
    type: Type.Int16,
    permission: 'rw',
  }),
  engine4FuelFlowLbHourSSL: new Offset({
    value: 0xA68,
    name: 'engine4FuelFlowLbHourSSL',
    category: OffsetCategory.ENGINE,
    description: 'engine4 fuel flow (lb per hour, sea level)',
    convert: '{VAL} / 128',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine4AntiIce: new Offset({
    value: 0xA7A,
    name: 'engine4AntiIce',
    category: OffsetCategory.ENGINE,
    description: 'engine4 anti-ice/carb heat active',
    convert: '!!{VAL}',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine4OilTemp: new Offset({
    value: 0xA80,
    name: 'engine4OilTemp',
    category: OffsetCategory.ENGINE,
    description: 'engine4 oil temp - celsius',
    convert: 'Math.round({VAL} * 140 / 16384)',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine4OilPres: new Offset({
    value: 0xA82,
    name: 'engine4OilPres',
    category: OffsetCategory.ENGINE,
    description: 'engine4 oil pressure - PSI',
    convert: 'Math.round({VAL} * 55 / 16384)',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine4PressureRatio: new Offset({
    value: 0xA84,
    name: 'engine4PressureRatio',
    category: OffsetCategory.ENGINE,
    description: 'engine4 pressure ratio',
    convert: '{VAL} * 1.6 / 16384',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine4EGT: new Offset({
    value: 0xA86,
    name: 'engine4EGT',
    category: OffsetCategory.ENGINE,
    description: 'engine4 exhaust gas temperature - Trust only on jet engine - celsius',
    convert: 'Math.round({VAL} * 860 / 16384)',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine4MP: new Offset({
    value: 0xA88,
    name: 'engine4MP',
    category: OffsetCategory.ENGINE,
    description: 'engine4 manifold pressure - inHg',
    convert: '{VAL} / 1024',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine4RPMScaler: new Offset({
    value: 0xA90,
    name: 'engine4RPMScaler',
    category: OffsetCategory.ENGINE,
    description: 'engine4 RPM Scaler - props: used to calculate RPM',
    type: Type.UInt16,
    permission: 'r',
  }),
  engine4OilQuantity: new Offset({
    value: 0xA98,
    name: 'engine4OilQuantity',
    category: OffsetCategory.ENGINE,
    description: 'engine4 oil quantity - percent',
    convert: 'Math.round({VAL} / 16384 * 100)',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine4Vibration: new Offset({
    value: 0xA9C,
    name: 'engine4Vibration',
    category: OffsetCategory.ENGINE,
    description: 'engine4 vibration',
    convert: 'Math.round({VAL} * 5 / 16384)',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine4HydPres: new Offset({
    value: 0xAA0,
    name: 'engine4HydPres',
    category: OffsetCategory.ENGINE,
    description: 'engine4 hydraulic pressure - PSI',
    convert: '{VAL} / 4',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine4HydQuantity: new Offset({
    value: 0xAA4,
    name: 'engine4HydQuantity',
    category: OffsetCategory.ENGINE,
    description: 'engine4 hydraulic quantity - percent',
    convert: '{VAL} / 16384 * 100',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine4CHT: new Offset({
    value: 0xAB0,
    name: 'engine4CHT',
    category: OffsetCategory.ENGINE,
    description: 'engine4 cylinder head temperature - F',
    type: Type.Double,
    permission: 'r',
  }),
  engine4ITT: new Offset({
    value: 0xAB8,
    name: 'engine4ITT',
    category: OffsetCategory.ENGINE,
    description: 'engine4 turbine temperature - C',
    convert: '{VAL} / 16384',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine4Torque: new Offset({
    value: 0xABC,
    name: 'engine4Torque',
    category: OffsetCategory.ENGINE,
    description: 'engine4 torque - trust only for helo - percent',
    convert: '{VAL} / 16384 * 100',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine4FuelPres: new Offset({
    value: 0xAC0,
    name: 'engine4FuelPres',
    category: OffsetCategory.ENGINE,
    description: 'engine4 fuel pressure - PSI',
    convert: '{VAL} / 144',
    type: Type.UInt32,
    permission: 'r',
  }),
  engine4FuelUsedSinceStart: new Offset({
    value: 0xAD4,
    name: 'engine4FuelUsedSinceStart',
    category: OffsetCategory.ENGINE,
    description: 'engine4 used fuel since start - lb',
    type: Type.Single,
    permission: 'r',
  }),
  engine4FuelElapsedTime: new Offset({
    value: 0xAD8,
    name: 'engine4FuelElapsedTime',
    category: OffsetCategory.ENGINE,
    description: 'engine4 fuel elapsed time - h',
    type: Type.Single,
    permission: 'r',
  }),
  engine4FuelFlowLbHour: new Offset({
    value: 0xAE0,
    name: 'engine4FuelFlowLbHour',
    category: OffsetCategory.ENGINE,
    description: 'engine4 fuel elapsed time - lb/h',
    type: Type.Double,
    permission: 'r',
  }),
  engine4TorqueFtLb: new Offset({
    value: 0xAE8,
    name: 'engine4TorqueFtLb',
    category: OffsetCategory.ENGINE,
    description: 'engine4 fuel elapsed time - ft lb',
    type: Type.Single,
    permission: 'r',
  }),
};
