export enum FuelTank {
  NONE = 'none',
  ALL = 'all',
  LEFT = 'left',
  RIGHT = 'right',
  LEFT_AUX = 'leftAux',
  RIGHT_AUX = 'rightAux',
  CENTER = 'center',
  CENTER2 = 'center2',
  CENTER3 = 'center3',
  EXT1 = 'ext1',
  EXT2 = 'ext2',
  RIGHT_TIP = 'rightTip',
  LEFT_TIP = 'leftTip',
  CROSS_FEED = 'crossFeed',
  CROSS_FEED_LTR = 'crossFeedLTR',
  CROSS_FEED_RTL = 'crossFeedRTL',
  CROSS_FEED_BOTH = 'crossFeedBoth',
  EXTERNAL = 'external',
  ISOLATE = 'isolate',
  LEFT_MAIN = 'leftMain',
  RIGHT_MAIN = 'rightMain',
}
