import { Type } from 'fsuipc';

import { OffsetList } from '@shared/offset-list';
import { Offset } from '@shared/offset';
import { OffsetCategory } from '@shared/offset-category';

export const weatherSettings: OffsetList = {
  upperCloudCeilingSetting: new Offset({
    value: 0xF1C,
    name: 'upperCloudCeilingSetting',
    category: OffsetCategory.WEATHER,
    description: 'upper cloud layer ceiling - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  upperCloudBaseSetting: new Offset({
    value: 0xF1E,
    name: 'upperCloudBaseSetting',
    category: OffsetCategory.WEATHER,
    description: 'upper cloud layer base - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  upperCloudCoverageSetting: new Offset({
    value: 0xF20,
    name: 'upperCloudCoverageSetting',
    category: OffsetCategory.WEATHER,
    description: 'upper cloud layer coverage - oktas - setting',
    convert: 'Math.round(({VAL} + 1) / 8192)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  upperCloudVariationSetting: new Offset({
    value: 0xF22,
    name: 'upperCloudVariationSetting',
    category: OffsetCategory.WEATHER,
    description: 'upper cloud layer variation - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  lowerCloudCeilingSetting: new Offset({
    value: 0xF24,
    name: 'lowerCloudCeilingSetting',
    category: OffsetCategory.WEATHER,
    description: 'lower cloud layer ceiling - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  lowerCloudBaseSetting: new Offset({
    value: 0xF26,
    name: 'lowerCloudBaseSetting',
    category: OffsetCategory.WEATHER,
    description: 'lower cloud layer base - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  lowerCloudCoverageSetting: new Offset({
    value: 0xF28,
    name: 'lowerCloudCoverageSetting',
    category: OffsetCategory.WEATHER,
    description: 'lower cloud layer coverage - oktas - setting',
    convert: 'Math.round(({VAL} + 1) / 8192)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  lowerCloudVariationSetting: new Offset({
    value: 0xF2A,
    name: 'lowerCloudVariationSetting',
    category: OffsetCategory.WEATHER,
    description: 'lower cloud layer variation - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  stormCloudCeilingSetting: new Offset({
    value: 0xF2C,
    name: 'stormCloudCeilingSetting',
    category: OffsetCategory.WEATHER,
    description: 'storm cloud layer ceiling - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  stormCloudBaseSetting: new Offset({
    value: 0xF2E,
    name: 'stormCloudBaseSetting',
    category: OffsetCategory.WEATHER,
    description: 'storm cloud layer base - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  stormCloudCoverageSetting: new Offset({
    value: 0xF30,
    name: 'stormCloudCoverageSetting',
    category: OffsetCategory.WEATHER,
    description: 'storm cloud layer coverage - oktas - setting',
    convert: 'Math.round(({VAL} + 1) / 8192)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  stormCloudVariationSetting: new Offset({
    value: 0xF32,
    name: 'stormCloudVariationSetting',
    category: OffsetCategory.WEATHER,
    description: 'storm cloud layer variation - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  upperTemperatureLevelSetting: new Offset({
    value: 0xF34,
    name: 'upperTemperatureLevelSetting',
    category: OffsetCategory.WEATHER,
    description: 'upper temperature level - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  upperTemperatureSetting: new Offset({
    value: 0xF36,
    name: 'upperTemperatureSetting',
    category: OffsetCategory.WEATHER,
    description: 'upper temperature - degrees C - setting',
    convert: 'Math.round({VAL} / 256)',
    type: Type.Int16,
    permission: 'rw',
  }),
  middleTemperatureLevelSetting: new Offset({
    value: 0xF38,
    name: 'middleTemperatureLevelSetting',
    category: OffsetCategory.WEATHER,
    description: 'middle temperature level - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  middleTemperatureSetting: new Offset({
    value: 0xF3A,
    name: 'middleTemperatureSetting',
    category: OffsetCategory.WEATHER,
    description: 'middle temperature - degrees C - setting',
    convert: 'Math.round({VAL} / 256)',
    type: Type.Int16,
    permission: 'rw',
  }),
  lowerTemperatureLevelSetting: new Offset({
    value: 0xF3C,
    name: 'lowerTemperatureLevelSetting',
    category: OffsetCategory.WEATHER,
    description: 'lower temperature level - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  lowerTemperatureSetting: new Offset({
    value: 0xF3E,
    name: 'lowerTemperatureSetting',
    category: OffsetCategory.WEATHER,
    description: 'lower temperature - degrees C - setting',
    convert: 'Math.round({VAL} / 256)',
    type: Type.Int16,
    permission: 'rw',
  }),
  surfaceTemperatureLevelSetting: new Offset({
    value: 0xF40,
    name: 'surfaceTemperatureLevelSetting',
    category: OffsetCategory.WEATHER,
    description: 'surface temperature level - ground elevation  - setting- ft',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  surfaceTemperatureSetting: new Offset({
    value: 0xF42,
    name: 'surfaceTemperatureSetting',
    category: OffsetCategory.WEATHER,
    description: 'surface temperature - degrees C - setting',
    convert: 'Math.round({VAL} / 256)',
    type: Type.Int16,
    permission: 'rw',
  }),
  temperatureDriftSetting: new Offset({
    value: 0xF44,
    name: 'temperatureDriftSetting',
    category: OffsetCategory.WEATHER,
    description: 'temperature drift - degrees C - setting',
    convert: 'Math.round({VAL} / 256)',
    type: Type.Int16,
    permission: 'rw',
  }),
  temperatureDayNightVariationSetting: new Offset({
    value: 0xF46,
    name: 'temperatureDayNightVariationSetting',
    category: OffsetCategory.WEATHER,
    description: 'temperature day night variation - degrees C - setting',
    convert: 'Math.round({VAL} / 256)',
    type: Type.Int16,
    permission: 'rw',
  }),
  pressureQNHSetting: new Offset({
    value: 0xF48,
    name: 'pressureQNHSetting',
    category: OffsetCategory.WEATHER,
    description: 'pressure QNH - mb - setting',
    convert: 'Math.round({VAL} / 16)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  pressureDriftSetting: new Offset({
    value: 0xF4A,
    name: 'pressureDriftSetting',
    category: OffsetCategory.WEATHER,
    description: 'pressure drift - mb - setting',
    convert: 'Math.round({VAL} / 16)',
    type: Type.Int16,
    permission: 'rw',
  }),
  upperWindCeilingSetting: new Offset({
    value: 0xF4C,
    name: 'upperWindCeilingSetting',
    category: OffsetCategory.WEATHER,
    description: 'upper wind ceiling - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  upperWindBaseSetting: new Offset({
    value: 0xF4E,
    name: 'upperWindBaseSetting',
    category: OffsetCategory.WEATHER,
    description: 'upper wind ceiling - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  upperWindSpeedSetting: new Offset({
    value: 0xF50,
    name: 'upperWindSpeedSetting',
    category: OffsetCategory.WEATHER,
    description: 'upper wind ceiling - kt - setting',
    type: Type.UInt16,
    permission: 'rw',
  }),
  upperWindDirectionSetting: new Offset({
    value: 0xF52,
    name: 'upperWindDirectionSetting',
    category: OffsetCategory.WEATHER,
    description: 'upper wind ceiling - TRUE degrees - setting',
    convert: '+({VAL} * 360 / 65536).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  upperWindTurbulenceSetting: new Offset({
    value: 0xF54,
    name: 'upperWindTurbulenceSetting',
    category: OffsetCategory.WEATHER,
    description: 'upper wind turbulence - 0-255 - setting',
    type: Type.UInt16,
    permission: 'rw',
  }),
  upperWindGustEnabledSetting: new Offset({
    value: 0xF56,
    name: 'upperWindGustEnabledSetting',
    category: OffsetCategory.WEATHER,
    description: 'upper wind gust enabled - setting',
    convert: '!!{VAL}',
    type: Type.UInt16,
    permission: 'rw',
  }),
  middleWindCeilingSetting: new Offset({
    value: 0xF58,
    name: 'middleWindCeilingSetting',
    category: OffsetCategory.WEATHER,
    description: 'middle wind ceiling - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  middleWindBaseSetting: new Offset({
    value: 0xF5A,
    name: 'middleWindBaseSetting',
    category: OffsetCategory.WEATHER,
    description: 'middle wind ceiling - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  middleWindSpeedSetting: new Offset({
    value: 0xF5C,
    name: 'middleWindSpeedSetting',
    category: OffsetCategory.WEATHER,
    description: 'middle wind ceiling - kt - setting',
    type: Type.UInt16,
    permission: 'rw',
  }),
  middleWindDirectionSetting: new Offset({
    value: 0xF5E,
    name: 'middleWindDirectionSetting',
    category: OffsetCategory.WEATHER,
    description: 'middle wind ceiling - TRUE degrees - setting',
    convert: '+({VAL} * 360 / 65536).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  middleWindTurbulenceSetting: new Offset({
    value: 0xF60,
    name: 'middleWindTurbulenceSetting',
    category: OffsetCategory.WEATHER,
    description: 'middle wind turbulence - 0-255 - setting',
    type: Type.UInt16,
    permission: 'rw',
  }),
  middleWindGustEnabledSetting: new Offset({
    value: 0xF62,
    name: 'middleWindGustEnabledSetting',
    category: OffsetCategory.WEATHER,
    description: 'middle wind gust enabled - setting',
    convert: '!!{VAL}',
    type: Type.UInt16,
    permission: 'rw',
  }),
  lowerWindCeilingSetting: new Offset({
    value: 0xF64,
    name: 'lowerWindCeilingSetting',
    category: OffsetCategory.WEATHER,
    description: 'lower wind ceiling - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  lowerWindBaseSetting: new Offset({
    value: 0xF66,
    name: 'lowerWindBaseSetting',
    category: OffsetCategory.WEATHER,
    description: 'lower wind ceiling - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  lowerWindSpeedSetting: new Offset({
    value: 0xF68,
    name: 'lowerWindSpeedSetting',
    category: OffsetCategory.WEATHER,
    description: 'lower wind ceiling - kt - setting',
    type: Type.UInt16,
    permission: 'rw',
  }),
  lowerWindDirectionSetting: new Offset({
    value: 0xF6A,
    name: 'lowerWindDirectionSetting',
    category: OffsetCategory.WEATHER,
    description: 'lower wind ceiling - TRUE degrees - setting',
    convert: '+({VAL} * 360 / 65536).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  lowerWindTurbulenceSetting: new Offset({
    value: 0xF6C,
    name: 'lowerWindTurbulenceSetting',
    category: OffsetCategory.WEATHER,
    description: 'lower wind turbulence - 0-255 - setting',
    type: Type.UInt16,
    permission: 'rw',
  }),
  lowerWindGustEnabledSetting: new Offset({
    value: 0xF6E,
    name: 'lowerWindGustEnabledSetting',
    category: OffsetCategory.WEATHER,
    description: 'lower wind gust enabled - setting',
    convert: '!!{VAL}',
    type: Type.Int16,
    permission: 'rw',
  }),
  surfaceWindCeilingSetting: new Offset({
    value: 0xF70,
    name: 'surfaceWindCeilingSetting',
    category: OffsetCategory.WEATHER,
    description: 'surface wind ceiling - ft - setting',
    convert: '+({VAL} * 3.28084).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  surfaceWindSpeedSetting: new Offset({
    value: 0xF72,
    name: 'surfaceWindSpeedSetting',
    category: OffsetCategory.WEATHER,
    description: 'surface wind speed - kt - settings',
    type: Type.UInt16,
    permission: 'rw',
  }),
  surfaceWindDirectionSetting: new Offset({
    value: 0xF74,
    name: 'surfaceWindSpeedSetting',
    category: OffsetCategory.WEATHER,
    description: 'surface wind direction - MAG degrees - settings',
    convert: '+({VAL} * 360 / 65536).toFixed(2)',
    type: Type.UInt16,
    permission: 'rw',
  }),
  surfaceWindTurbulenceSetting: new Offset({
    value: 0xF76,
    name: 'surfaceWindTurbulenceSetting',
    category: OffsetCategory.WEATHER,
    description: 'surface wind turbulence - 0-255 - setting',
    type: Type.UInt16,
    permission: 'rw',
  }),
  surfaceWindGustEnabledSetting: new Offset({
    value: 0xF78,
    name: 'surfaceWindGustEnabledSetting',
    category: OffsetCategory.WEATHER,
    description: 'surface wind gust enabled - setting',
    convert: '!!{VAL}',
    type: Type.UInt16,
    permission: 'rw',
  }),
  upperCloudTypeSetting: new Offset({
    value: 0xF7A,
    name: 'upperCloudTypeSetting',
    category: OffsetCategory.WEATHER,
    description: 'upper cloud type - setting',
    convert: 'cloudType',
    mapping: true,
    type: Type.UInt16,
    permission: 'rw',
  }),
  upperCloudIcingSetting: new Offset({
    value: 0xF7C,
    name: 'upperCloudIcingSetting',
    category: OffsetCategory.WEATHER,
    description: 'upper cloud icing - setting',
    convert: '!!{VAL}',
    type: Type.UInt16,
    permission: 'rw',
  }),
  upperCloudTurbulenceSetting: new Offset({
    value: 0xF7E,
    name: 'upperCloudTurbulenceSetting',
    category: OffsetCategory.WEATHER,
    description: 'upper cloud turbulence - 0-255 - setting',
    type: Type.UInt16,
    permission: 'rw',
  }),
  lowerCloudTypeSetting: new Offset({
    value: 0xF80,
    name: 'lowerCloudTypeSetting',
    category: OffsetCategory.WEATHER,
    description: 'lower cloud type - setting',
    convert: 'cloudType',
    mapping: true,
    type: Type.UInt16,
    permission: 'rw',
  }),
  lowerCloudIcingSetting: new Offset({
    value: 0xF82,
    name: 'lowerCloudIcingSetting',
    category: OffsetCategory.WEATHER,
    description: 'lower cloud icing - setting',
    convert: '!!{VAL}',
    type: Type.UInt16,
    permission: 'rw',
  }),
  lowerCloudTurbulenceSetting: new Offset({
    value: 0xF84,
    name: 'lowerCloudTurbulenceSetting',
    category: OffsetCategory.WEATHER,
    description: 'lower cloud turbulence - 0-255 - setting',
    type: Type.UInt16,
    permission: 'rw',
  }),
  stormCloudTypeSetting: new Offset({
    value: 0xF86,
    name: 'stormCloudTypeSetting',
    category: OffsetCategory.WEATHER,
    description: 'storm cloud type - setting',
    convert: 'cloudType',
    mapping: true,
    type: Type.UInt16,
    permission: 'rw',
  }),
  stormCloudIcingSetting: new Offset({
    value: 0xF88,
    name: 'stormCloudIcingSetting',
    category: OffsetCategory.WEATHER,
    description: 'storm cloud icing - setting',
    convert: '!!{VAL}',
    type: Type.UInt16,
    permission: 'rw',
  }),
  stormCloudTurbulenceSetting: new Offset({
    value: 0xF8A,
    name: 'stormCloudTurbulenceSetting',
    category: OffsetCategory.WEATHER,
    description: 'storm cloud turbulence - 0-255 - setting',
    type: Type.UInt16,
    permission: 'rw',
  }),
  visibilitySetting: new Offset({
    value: 0xF8C,
    name: 'visibilitySetting',
    category: OffsetCategory.WEATHER,
    description: 'visibility setting - sm',
    convert: '{VAL} / 100',
    type: Type.UInt16,
    permission: 'rw',
  }),
};
