name: branch-master
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    name: lint
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - name: setup:checkout
        uses: actions/checkout@master
      - name: setup:python3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: x64
      - name: setup:cache:node
        uses: actions/cache@v1.1.0
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-api-test-node-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-api-test-node-
            ${{ runner.os }}-api-
      - name: deps:install
        shell: bash
        run: |
          yarn
      - name: test:lint
        shell: bash
        run: |
          yarn tslint

  test:
    name: test
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - name: setup:checkout
        uses: actions/checkout@master
      - name: setup:python3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: x64
      - name: setup:cache:node
        uses: actions/cache@v1.1.0
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-api-test-node-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-api-test-node-
            ${{ runner.os }}-api-
      - name: deps:install
        shell: bash
        run: |
          yarn
      - name: test:unit
        shell: bash
        run: |
          yarn test:ci
      - name: test:coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/coverage/lcov.info

  build:
    name: build
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - name: setup:checkout
        uses: actions/checkout@master
      - name: setup:python3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: x64
      - name: setup:cache
        uses: actions/cache@v1.1.0
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-api-build-node-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-api-build-node-
            ${{ runner.os }}-api-
      - name: deps:install
        shell: bash
        run: |
          yarn
      - name: build:prod
        shell: bash
        run: |
          yarn compile:prod
      - name: build:upload:artifacts
        if: github.base_ref == 0
        uses: actions/upload-artifact@v1
        with:
          name: fsuipc-api-${{ github.sha }}
          path: ${{ github.workspace }}/dist
